version: '2.1'
services:
  client:
    image: effectivetrainings/counter-app
    environment:
    - server_url=http://server:8080/counter
    - application_server=false
    networks:
    - effectivedocker
    ports:
    - 8080:8080
    depends_on:
      server:
        condition: service_healthy
    healthcheck:
       test: "curl -f localhost:8080/health || exit 1"
  server:
      image: effectivetrainings/counter-app
      networks:
      - effectivedocker
      environment:
      - application_server=true
      healthcheck:
        test: "curl -f localhost:8080/health || exit 1"
networks:
   effectivedocker:
    driver: bridge